# Generated by Django 4.2.2 on 2023-06-16 20:29

from django.db import migrations, models
import django.db.models.deletion
import product_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog_api', '0003_alter_subcategory_parent'),
        ('tags_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular', models.BooleanField(default=False)),
                ('sale', models.BooleanField(default=False)),
                ('limited', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=200)),
                ('full_description', models.TextField()),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('free_delivery', models.BooleanField(default=False)),
                ('images', models.ImageField(upload_to=product_api.models.upload_path_images)),
                ('title', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog_api.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog_api.subcategory')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='tags_api.tags')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
