# Generated by Django 4.2.2 on 2023-06-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0002_alter_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
