# Generated by Django 4.2.2 on 2023-06-18 18:37

from django.db import migrations, models
import django.db.models.deletion
import product_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0011_alter_review_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specifications', to='product_api.specifications'),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=product_api.models.upload_path_images)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='product_api.product')),
            ],
            options={
                'verbose_name': 'Изображение продукта',
                'verbose_name_plural': 'Изображения продуктоа',
            },
        ),
    ]
