# Generated by Django 4.2.2 on 2023-06-18 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0012_alter_product_specifications_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
