# Generated by Django 4.2.2 on 2023-06-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0013_remove_product_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='new_price',
            new_name='salePrice',
        ),
        migrations.AddField(
            model_name='product',
            name='dateFrom',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dateTo',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
