# Generated by Django 4.2.2 on 2023-06-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0014_rename_new_price_product_saleprice_product_datefrom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
