# Generated by Django 4.2.2 on 2023-06-15 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0002_alter_profile_avatar_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
