# Generated by Django 4.2.2 on 2023-06-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0003_alter_profile_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fullname',
            new_name='fullName',
        ),
    ]
