# Generated by Django 4.2.2 on 2023-06-19 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_api', '0014_rename_new_price_product_saleprice_product_datefrom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('deliveryType', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], max_length=50)),
                ('paymentType', models.CharField(choices=[('online', 'Online'), ('paid', 'Paid')], max_length=50)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('processing', 'Processing'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=50)),
                ('city', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=256)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_api.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_api.product')),
            ],
            options={
                'verbose_name': 'Продукт в заказе',
                'verbose_name_plural': 'Продукты в заказе',
            },
        ),
    ]
