# Generated by Django 4.2.2 on 2023-08-05 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="deliveryType",
            field=models.CharField(
                choices=[
                    ("Экспресс доставка", "Экспресс доставка"),
                    ("Обычная доставка", "Обычная доставка"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="paymentType",
            field=models.CharField(
                choices=[
                    ("Онлайн оплата", "Онлайн оплата"),
                    ("Оплата наличными", "Оплата наличными"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Подтвержден", "Подтвержден"),
                    ("Оплачен", "Оплачен"),
                    ("Отменен", "Отменен"),
                    ("Завершен", "Завершен"),
                    ("Создан", "Создан"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products_in_order",
                to="orders_api.order",
            ),
        ),
    ]
