# Generated by Django 4.2.2 on 2023-06-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_api', '0002_alter_order_paymenttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_cost',
            new_name='totalCost',
        ),
    ]
