# Generated by Django 4.2.2 on 2023-06-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_api', '0005_alter_orderproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentType',
            field=models.CharField(choices=[('online', 'Online'), ('someone', 'Someone')], max_length=50),
        ),
    ]
