# Generated by Django 4.2.2 on 2023-06-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_api', '0007_alter_order_deliverytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('processing', 'Processing'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('created', 'Created')], max_length=50),
        ),
    ]
